#eureka:
#  instance:
#    host: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#server:
#  port: 8070
spring:
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/schools
#    username: gbolaga
#    password: ayokunle
#  jpa:
#    hibernate:
#      ddl-auto: 'update'
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#application:
#  config:
    # we can use 8090 as well. just that 8222 means we are connection via the Gateway instead of directly
#    students-url: http://localhost:8222/api/v1/students
