server:
  port: 8888

spring:
  profiles:
    active: native # To automatically use the native active profile.
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
